### ISSUE TITLE
Help with 'sendMessage'

### ISSUE THREAD

**Issue by nealgist** [RocketChat/botpress-channel-rocketchat#13]
Hi there, I'm not sure where certain code is supposed to go in order to work. In the docs under outgoing it says: 

"In code, it is simple to send a message text to a specific users or channels."
`sendMessage(msg, options, event) -> Promise`

Where can this sendMessage function be called? I've tried calling it in `actions.js` but it is undefined. I see that it is a function inside of the RocketChat class in `rocketchat.js`, but I'm not sure how to access it. Can you help me see what I'm missing? Thank you!

p.s. If there is an example rocketchat demo featuring botpress-channel-rocketchat with working examples, that would be amazing to be able to see the code and gain understanding!

**Comment by monkey3101** [comment]
Its sendText base on bp.rocketchat.sendText
